> library('sleuth')
> base_dir = "/home/linux/ieng6/oce/8m/ljervis/FinalProject/KallistoOutputTrimmedNC_009085.1"
> sample_dir = dir(file.path(base_dir))
> kal_dirs = sapply(sample_dir, function(id) file.path(base_dir, id))
> s2c = read.table(file.path("/home/linux/ieng6/oce/8m/ljervis/FinalProject/scripts/exp_info.txt"),header=TRUE,stringsAsFactors=FALSE)
> s2c = dplyr::select(s2c,sample=sample, condition, reps)
> s2c = dplyr::mutate(s2c, path=kal_dirs)
> so = sleuth_prep(s2c,~ condition, extra_bootstrap_summary=TRUE)
> so = sleuth_fit(so)
> so = sleuth_fit(so,~1,'reduced')
> so = sleuth_lrt(so,'reduced','full')
> sleuth_table = sleuth_results(so, 'reduced:full', 'lrt', show_all = FALSE)
> sleuth_significant <- dplyr::filter(sleuth_table, qval <= 0.05)
> so = sleuth_wt(so,'conditionPlanktonic','full')
> results_table <- sleuth_results(so, 'conditionPlanktonic', test_type = 'wt')
> sleuth_significant <- dplyr::filter(results_table, qval <= 0.05)
